config/routes.rb
Rails.application.routes.draw do

  resources :urls, only: [:index, :show, :new, :create, :destroy]

  root 'urls#new'

  get ':shortened_url', to: 'short_url#redirect', format: false,
    constraints: { shortened_url: /[A-Za-z0-9]{6}/ }, as: 'short'

end

app/models/url.rb
require 'uri'
require 'securerandom'

# Keeps track of a URL and its shortened version
class Url < ActiveRecord::Base
  before_validation :set_shortened, :strip_spaces

  validates :original, presence: true, uniqueness: true,
     format: { with: %r{\Ahttps?://\S+\Z}, message: 'Invalid URL' }
  validates :shortened, uniqueness: true, length: { minimum: 6, maximum: 6 }
  validate :check_format

  def self.generate_unique
    loop do
      short = SecureRandom.base64.gsub(/[\/=]/, '')[0, 6]
      next if short !~ /\A[A-Za-z0-9]{6}\Z/
      return short unless find_by(shortened: short)
    end
  end

  def self.to_uri(url)
    URI.parse(url) rescue nil
  end

  def check_format
    return if self.class.to_uri(original)
    errors.add(:original, 'Invalid Format URL')
  end

  def strip_spaces
    return unless original
    original.strip!
  end

  def set_shortened
    return unless original
    self.shortened = self.class.generate_unique unless shortened
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/short_url_controller.rb
# Redirects a shrotened URL to the original URL
class ShortUrlController < ApplicationController
  def redirect
    @url = Url.find_by(shortened: params[:shortened_url])
    if @url
      redirect_to @url.original
    else
      render text: "No Route Matched: #{params[:shortened_url]}", status: 404
    end
  end
end

app/controllers/urls_controller.rb
# Handles a URL submitted by a user
class UrlsController < ApplicationController
  def index
    @urls = Url.all
  end

  def show
    @url = Url.find_by(id: params[:id].to_i) || Url.new
  end

  def new
    @url ||= Url.new
  end

  def create
    @url = Url.find_or_initialize_by(original: url_params[:original])
    if @url.new_record?
      if @url.save
        redirect_to @url
      else
        render :new
      end
    else
      redirect_to @url
    end
  end

  def destroy
    @url = Url.find_by(id: params[:id])
    @url.destroy if @url
    redirect_to urls_path
  end

  private

  def url_params
    params.require(:url).permit(:original)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_url_helper.rb
module ShortUrlHelper
end

app/helpers/urls_helper.rb
# Urls Helper
module UrlsHelper
  def fullpath(shortened)
    "http://#{current_host}/#{shortened}"
  end

  def current_host
    host = request.host
    host += ":#{request.port}" if request.port
    host
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1' }
    %title= content_for?(:title) ? yield(:title) : "URL Shortener"
    %meta{ content: content_for?(:description) ? yield(:description) : "URL Shortener", name: 'description' }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/urls/index.html.haml
.row
%h1.col4 URL List
%p.col4= link_to 'Generate a short URL', new_url_path

- if @urls.length > 0
  %table.nicetbl
    %tr
      %th URL
      %th Shortened
      %th
      %th
    - @urls.each do |url|
      %tr
        %td.col-sm-4= raw url.original
        %td.col-sm-4= raw fullpath(url.shortened)
        %td.col-sm-1= link_to 'Show', url_path(url)
        %td.col-sm-1= link_to 'Delete', url_path(url), method: :delete, data: { confirm: 'Are you sure?'}

app/views/urls/new.html.haml
.row
  %h1.col4 URL Shortener
.row
  = form_for @url, html: { class: 'form-horizontal' } do |f|
    .form-group
      .input-group.col6
        = f.text_field :original, class: 'form-control input-lg', placeholder: 'Enter URL'
        %span.input-group-btn
          = f.button 'Generate', class: 'btn btn-primary btn-lg'

- if @url.errors.any?
  #error_explanation.row
    .col4.text-danger
      %p URL was not saved due to next #{ pluralize(@url.errors.count, 'error') }
      %ul
        - @url.errors.full_messages.each do |msg|
          %li= msg 

.row
  %p.col6= link_to 'Show List', urls_path

app/views/urls/show.html.haml
.row
  %h1.col4 URL Shortener
  %p.col6
    %strong Original URL:
    = raw @url.original
  %p.col6
    %strong Shortened URL:
    = raw fullpath(@url.shortened)
  %p.col6
    = link_to 'Show List', urls_path
  %p.col6
    = link_to 'Generate a short URL', new_url_path